/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio_2;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author me50r
 */
public class GestionDeProductos extends javax.swing.JInternalFrame {
    // Crea el modelo por default
    private DefaultTableModel modelo = new DefaultTableModel(){
        //Sobreescribir metodo de la clase para hacer que las celdas no sean editabes
        @Override
        public boolean isCellEditable(int f, int c){
            return false;
        }
    };
    /**
     * Creates new form GestionDeProductos
     */
    public GestionDeProductos() {
        initComponents();
        cargarCategorias();
        agregarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JL_gestion = new javax.swing.JLabel();
        JL_filtrar = new javax.swing.JLabel();
        JCB_categoria = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        JT_tablita = new javax.swing.JTable();
        JP_contenedor = new javax.swing.JPanel();
        Jl_codigo = new javax.swing.JLabel();
        JL_descripcion = new javax.swing.JLabel();
        JL_precio = new javax.swing.JLabel();
        JL_rubro = new javax.swing.JLabel();
        JL_stock = new javax.swing.JLabel();
        JTF_codigo = new javax.swing.JTextField();
        JTF_descripcion = new javax.swing.JTextField();
        JTF_precio = new javax.swing.JTextField();
        JCB_rubro = new javax.swing.JComboBox<>();
        JS_stock = new javax.swing.JSpinner();
        JB_cerrar = new javax.swing.JButton();
        JB_nuevo = new javax.swing.JButton();
        JB_guardar = new javax.swing.JButton();
        JB_actualizar = new javax.swing.JButton();
        JB_eliminar = new javax.swing.JButton();
        JB_buscar = new javax.swing.JButton();

        setClosable(true);

        JL_gestion.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        JL_gestion.setText("Gestion de productos");

        JL_filtrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        JL_filtrar.setText("Filtrar por categoria: ");

        JCB_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCB_categoriaActionPerformed(evt);
            }
        });

        JT_tablita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JT_tablita);

        JP_contenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Jl_codigo.setText("Codigo:");

        JL_descripcion.setText("Descripcion");

        JL_precio.setText("Precio");

        JL_rubro.setText("Rubro");

        JL_stock.setText("Stock");

        JTF_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTF_descripcionActionPerformed(evt);
            }
        });

        JS_stock.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        javax.swing.GroupLayout JP_contenedorLayout = new javax.swing.GroupLayout(JP_contenedor);
        JP_contenedor.setLayout(JP_contenedorLayout);
        JP_contenedorLayout.setHorizontalGroup(
            JP_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_contenedorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(JP_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JP_contenedorLayout.createSequentialGroup()
                        .addComponent(JL_descripcion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTF_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JP_contenedorLayout.createSequentialGroup()
                        .addComponent(Jl_codigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JTF_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JP_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(JP_contenedorLayout.createSequentialGroup()
                            .addComponent(JL_precio)
                            .addGap(18, 18, 18)
                            .addComponent(JTF_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JP_contenedorLayout.createSequentialGroup()
                            .addGroup(JP_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JL_stock)
                                .addComponent(JL_rubro))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(JP_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(JP_contenedorLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(JS_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(JCB_rubro, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        JP_contenedorLayout.setVerticalGroup(
            JP_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JP_contenedorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(JP_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jl_codigo)
                    .addComponent(JTF_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_descripcion)
                    .addComponent(JTF_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_precio)
                    .addComponent(JTF_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_rubro)
                    .addComponent(JCB_rubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JP_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL_stock)
                    .addComponent(JS_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        JB_cerrar.setText("Cerrar");
        JB_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_cerrarActionPerformed(evt);
            }
        });

        JB_nuevo.setText("Nuevo");
        JB_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_nuevoActionPerformed(evt);
            }
        });

        JB_guardar.setText("Guardar");
        JB_guardar.setEnabled(false);
        JB_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_guardarActionPerformed(evt);
            }
        });

        JB_actualizar.setText("Actualizar");

        JB_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eliminar.png"))); // NOI18N
        JB_eliminar.setText("Eliminar");

        JB_buscar.setText("Buscar");
        JB_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JB_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(JB_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JB_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JP_contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(JB_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(JB_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JL_filtrar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JL_gestion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCB_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(JL_gestion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JCB_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL_filtrar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(JB_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(JB_cerrar)
                        .addGap(94, 94, 94))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JP_contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JB_eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(JB_nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(JB_guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JB_actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JCB_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCB_categoriaActionPerformed
        
    }//GEN-LAST:event_JCB_categoriaActionPerformed

    private void JTF_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTF_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_descripcionActionPerformed

    private void JB_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_cerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_cerrarActionPerformed

    private void JB_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_nuevoActionPerformed
        int codigo = Integer.parseInt(JTF_codigo.getText());
        String descripcion = JTF_descripcion.getText();
        double precio = Double.parseDouble(JTF_precio.getText());
        Rubro categoria = (Rubro) JCB_rubro.getSelectedItem();
        int stock = (Integer) JS_stock.getValue();
        
        Producto producto = new Producto(codigo, descripcion, precio, stock, categoria);
        cargarDatos(producto);
    }//GEN-LAST:event_JB_nuevoActionPerformed

    private void JB_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_guardarActionPerformed
        
    }//GEN-LAST:event_JB_guardarActionPerformed

    private void JB_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JB_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB_actualizar;
    private javax.swing.JButton JB_buscar;
    private javax.swing.JButton JB_cerrar;
    private javax.swing.JButton JB_eliminar;
    private javax.swing.JButton JB_guardar;
    private javax.swing.JButton JB_nuevo;
    private javax.swing.JComboBox<String> JCB_categoria;
    private javax.swing.JComboBox<Rubro> JCB_rubro;
    private javax.swing.JLabel JL_descripcion;
    private javax.swing.JLabel JL_filtrar;
    private javax.swing.JLabel JL_gestion;
    private javax.swing.JLabel JL_precio;
    private javax.swing.JLabel JL_rubro;
    private javax.swing.JLabel JL_stock;
    private javax.swing.JPanel JP_contenedor;
    private javax.swing.JSpinner JS_stock;
    private javax.swing.JTextField JTF_codigo;
    private javax.swing.JTextField JTF_descripcion;
    private javax.swing.JTextField JTF_precio;
    private javax.swing.JTable JT_tablita;
    private javax.swing.JLabel Jl_codigo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    public void cargarCategorias(){
        JCB_categoria.addItem("Perfumeria");
        JCB_categoria.addItem("Comestible");
        JCB_categoria.addItem("Limpieza");
        JCB_rubro.addItem(Rubro.COMESTIBLE);
        JCB_rubro.addItem(Rubro.PERFUMERIA);
        JCB_rubro.addItem(Rubro.LIMPIEZA);
    }
    
        // Método para agregar cabeceras
    private void agregarCabecera() {
        modelo.addColumn("Codigo");
        modelo.addColumn("Descripcion");
        modelo.addColumn("Precio");
        modelo.addColumn("Categoria");
        modelo.addColumn("Stock");

        // Seteamos el modelo
        JT_tablita.setModel(modelo);
    }
    
    private void cargarDatos(Producto p) {
        modelo.addRow(new Object[]{p.getCodigo(), p.getDescripcion(), p.getPrecio(), p.getRubro(), p.getStock()});
        DeTodo_SA.listaDeProductos.add(p);
    }
}
