package tp2.grupo6;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class codigoSecreto extends javax.swing.JFrame {

    private static int intentos = 0;
    private static int ayudas = 0;
    private static int solucion = 0;
    private static int solu1;
    private static int solu2;
    private static int solu3;

    public codigoSecreto() {
        initComponents();

        solucion = (int) ((Math.random() * 900) + 100);
        solu1 = solucion / 100;
        solu2 = (solucion % 100) / 10;
        solu3 = solucion % 10;

        // TROFEO
        ImageIcon iconoOriginal = new ImageIcon(getClass()
                .getResource("/images/trofeo1.png"));
        // ImageIcon es la representación de memoria que utiliza Swing para manejar imágenes

        /*
        getScaledInstance sirve para ajustar la imagen a un cierto tamaño.
        getWidth y getHeight obtienen el alto y ancho del Label del objeto.
        SCALE_SMOOTH es para suavizar los bordes y no quede feo. 
         */
        Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(
                lblTrofeo.getWidth(),
                lblTrofeo.getHeight(),
                Image.SCALE_SMOOTH
        );
        /*
        Seteo el ícono del Trofeo ya ajustado al label
         */
        lblTrofeo.setIcon(new ImageIcon(imagenEscalada));
        lblTrofeo.setVisible(false);

        pasw1.setText(String.valueOf(solu1));
        pasw2.setText(String.valueOf(solu2));
        pasw3.setText(String.valueOf(solu3));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jf = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        pasw3 = new javax.swing.JPasswordField();
        pasw2 = new javax.swing.JPasswordField();
        pasw1 = new javax.swing.JPasswordField();
        lblAviso = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btRevelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tf = new javax.swing.JTextField();
        lblTf = new javax.swing.JLabel();
        lblTrofeo = new javax.swing.JLabel();

        jLabel2.setText("Código secreto");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TP2: Adivina el código secreto");

        jf.setToolTipText("");
        jf.setName(""); // NOI18N

        pasw3.setEditable(false);
        pasw3.setBackground(new java.awt.Color(255, 51, 51));
        pasw3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        pasw3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pasw3.setText("$");
        pasw3.setEchoChar('$');
        pasw3.setName("pf3"); // NOI18N

        pasw2.setEditable(false);
        pasw2.setBackground(new java.awt.Color(153, 255, 153));
        pasw2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        pasw2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pasw2.setText("$");
        pasw2.setEchoChar('$');
        pasw2.setName("pf2"); // NOI18N

        pasw1.setEditable(false);
        pasw1.setBackground(new java.awt.Color(255, 255, 153));
        pasw1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        pasw1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pasw1.setText("$");
        pasw1.setEchoChar('$');
        pasw1.setName("pf1"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pasw1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pasw2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(pasw3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pasw3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pasw2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pasw1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblAviso.setBackground(new java.awt.Color(255, 255, 255));
        lblAviso.setForeground(new java.awt.Color(255, 255, 255));
        lblAviso.setText("Por favor, ingresa exactamente 3 números");

        lblTitulo.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblTitulo.setText("Código secreto");

        btRevelar.setText("Revelar");
        btRevelar.setName("btRevelar"); // NOI18N
        btRevelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRevelarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        tf.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfActionPerformed(evt);
            }
        });
        tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfKeyReleased(evt);
            }
        });

        lblTf.setBackground(new java.awt.Color(255, 51, 51));
        lblTf.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTf.setText("Escribe 3 dígitos + enter");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tf)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 9, Short.MAX_VALUE)
                .addComponent(lblTf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblTrofeo.setBackground(new java.awt.Color(204, 204, 204));
        lblTrofeo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrofeo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trofeo1.png"))); // NOI18N
        lblTrofeo.setPreferredSize(new java.awt.Dimension(90, 90));

        jf.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jf.setLayer(lblAviso, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jf.setLayer(lblTitulo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jf.setLayer(btRevelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jf.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jf.setLayer(lblTrofeo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jfLayout = new javax.swing.GroupLayout(jf);
        jf.setLayout(jfLayout);
        jfLayout.setHorizontalGroup(
            jfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfLayout.createSequentialGroup()
                .addGroup(jfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jfLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jfLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jfLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btRevelar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(lblTrofeo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jfLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblAviso)
                .addGap(77, 77, 77))
        );
        jfLayout.setVerticalGroup(
            jfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jfLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAviso)
                .addGroup(jfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jfLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btRevelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jfLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jfLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTrofeo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lblAviso.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jf)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jf)
        );

        jf.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRevelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRevelarActionPerformed
        ayudas++;
        if (ayudas == 1) {
            pasw1.setEchoChar((char) 0);
        } else if (ayudas == 2) {
            pasw2.setEchoChar((char) 0);
        } else {
            JOptionPane.showMessageDialog(this, "Te quedaste sin revelaciones.");
            btRevelar.setEnabled(false);
        }
    }//GEN-LAST:event_btRevelarActionPerformed

    private void tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfActionPerformed
        // trim funciona para quitar espacios al principio y al final
        String textoIngresado = tf.getText().trim();

        if (textoIngresado.length() == 3) {
            intentos++;
            try {
                int intento = Integer.parseInt(textoIngresado);
                int dig1 = intento / 100;
                int dig2 = (intento % 100) / 10;
                int dig3 = intento % 10;

                if (solu1 == dig1) {
                    pasw1.setEchoChar((char) 0);
                }
                if (solu2 == dig2) {
                    pasw2.setEchoChar((char) 0);
                }
                if (solu3 == dig3) {
                    pasw3.setEchoChar((char) 0);
                }

                if (solu1 == dig1 && solu2 == dig2 && solu3 == dig3) {
                    lblTrofeo.setVisible(true);
                    JOptionPane.showMessageDialog(this, "¡Ganaste! "
                            + "\nEl código secreto: " + solucion
                            + "\nIntentos: " + intentos);
                    lblAviso.setText("¡Encontraste el código secreto!");
                } else if (solucion < intento) {
                    lblAviso.setText("El número secreto es un valor más bajo");
                } else {
                    lblAviso.setText("El número secreto es un valor más alto");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Ingresa solo números enteros");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes ingresar exáctamente 3 números.");
        }
    }//GEN-LAST:event_tfActionPerformed

    private void tfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKeyReleased
    }//GEN-LAST:event_tfKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(codigoSecreto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(codigoSecreto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(codigoSecreto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(codigoSecreto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new codigoSecreto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRevelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JDesktopPane jf;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblTf;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTrofeo;
    private javax.swing.JPasswordField pasw1;
    private javax.swing.JPasswordField pasw2;
    private javax.swing.JPasswordField pasw3;
    private javax.swing.JTextField tf;
    // End of variables declaration//GEN-END:variables
}
